#!/bin/sh
#
# bulk-config - Set/get configuration settings or MQTT topics
#
# Copyright (C) 2021 Linzhi Ltd.
#
# This work is licensed under the terms of the MIT License.
# A copy of the license can be found in the file COPYING.txt
#


DEFAULT_TIMEOUT_S=10

MOSQ_ERR_TIMEOUT=27


usage()
{
	cat <<EOF 1>&2
usage: $0 [-r] [-t seconds] [-w seconds] [-x]
          [0/|1/]var[=value]|/topic[?cond][=payload]
          [host|file ...]

-r  set the retain flag on the messages sent
-t seconds
    if retrieving, wait this many seconds before giving up (default: wait
    $DEFAULT_TIMEOUT_S seconds)
-w seconds
    wait this many seconds between publish/subscribe actions (default: don't
    wait)
-x  show shell commands (set -x)
EOF
	exit 1
}


sleep=:
retain=
timeout="-W $DEFAULT_TIMEOUT_S"
while [ "$1" ]; do
	case "$1" in
	-r)	retain=-r;;
	-t)	case "$2" in
		0)	timeout=;;
		"")	usage;;
		*)	timeout="-W $2";;	
		esac
		shift;;
	-w)	[ "$2" ] || usage
		sleep="sleep $2"
		shift;;
	-x)	set -x;;
	-*)	usage;;
	*)	break;;
	esac
	shift
done

[ "$2" ] || usage

var=${1%%=*}
val=${1#*=}

pub=true
if [ "$var" = "$1" ]; then
	pub=false
fi

shift

cond=${var##*\?}
if [ "$cond" = "$var" ]; then
	cond=
	have_cond=false
else
	have_cond=true
fi
var=${var%\?*}

topic=
case "$var" in
/*)	topic=$var;;
0/*)	area=user0
	var=${var#0/};;
1/*)	area=user1
	var=${var#1/};;
*)	area=user;;
esac

if [ "$topic" ]; then
	pub_topic=$topic
	sub_topic=$topic
else
	pub_topic=/config/$area/$var/set
	sub_topic=/config/$area/$var
	retain=
fi


op()
{
	local name=$1
	local pub_this=$pub

	if $have_cond; then
		pub_this=false
	fi
	if $have_cond || ! $pub; then
		res=`mosquitto_sub -h "$name" -t "$sub_topic" -C 1 $timeout \
		    -F "$name %p"`
		case "$?" in
		0)	payload=${res#* }
			if $have_cond && [ "$cond" = "$payload" ]; then
				echo "$res (MATCH)"
				pub_this=$pub
			else
				echo "$res"
			fi;;
		$MOSQ_ERR_TIMEOUT)
			to="$to $name"
			if $have_cond && [ -z "$cond" ]; then
				echo "$name: timeout (MATCH)"
				pub_this=$pub
			else
				echo "timeout: $name" 1>&2
			fi;;
		*)	echo "failed: $name" 1>&2
			failed="$failed $name"
			return;;
		esac
	fi
	if $pub_this; then
		mosquitto_pub -h "$name" -t "$pub_topic" -m "$val" \
		    -q 1 $retain || {
			echo "failed: $name" 1>&2
			failed="$failed $name"
		}
	fi
	$sleep
}


failed=
to=
for n in "$@"; do
	if [ -r "$n" ]; then
		for m in `awk '/^[^#]/ { print \$1 }' $n`; do
			op "$m"
		done
	else
		op "$n"
	fi
done

if [ "$failed" ]; then
	set - $failed
	echo "$# failed:$failed" 1>&2
fi
if [ "$to" ]; then
	set - $to
	echo "$# timeout:$to" 1>&2
fi
